### ISSUE TITLE
Mounting some images does not work and produces the same error message

### ISSUE THREAD

**Issue by SuperOkazaki** [ihaveamac/fuse-3ds#1]
Mounting some `cxi`, `cia`, and NAND backup files produce an error message saying
 
`AttributeError: 'CTRCartImageMount' object has no attribute 'f'`

In addition, the images do not mount. The game images are decrypted with GM9, and a correct `boot9.bin`, `boot9_prot.bin`, `nandcid.bin`, `otp.bin`, and `seeddb.bin` are provided.

I have gotten other files to work, but never a NAND backup. 

MacOS 10.2.6, Python 3.6.4

**Comment by ihaveamac** [comment]
can you post the full traceback/output?

**Comment by ihaveamac** [comment]
that happens in `__del__`, so it only happens when the interpreter is shutting down (fixed locally already).

if nothing is being displayed in the mount (or it's not being made at all), the issue is probably something else.

**Comment by ihaveamac** [comment]
also, "For cxi files" ... "CTRCartImageMount" make sure you're using the right mount type.

**Comment by SuperOkazaki** [comment]
My bad, I mean .cci. I always confuse those extensions.
Do you think something is configured wrong on my end? Some files work and some do not. I made a new dump of a cart and tried it again and it didn't work. In addition a fresh NAND backup from GM9 also makes the same error.

Is there any more info I can get you to troubleshoot?

**Comment by ihaveamac** [comment]
please dump the entire output of the program and post it here. you can save it to a file with a cmd like `mount_cci game.cci &> out.txt`. you can edit out sensitive parts of paths if you want.

**Comment by SuperOkazaki** [comment]
I think I figured out the problem. I reinstalled `pip`, Python3, and FUSE and rebooted and it seems to work now. I guess there was just something configured wrong. Thank you for attempting to help though, I appreciate it!
