### ISSUE TITLE
Run fail

### ISSUE THREAD

**Issue by david-zzj** [ihaveamac/fuse-3ds#10]
My OS is win10 64bit，winfsp and osfmount already install，but when i run the tool，it give me an error message like this. Do i miss something？

**Comment by david-zzj** [comment]
error message said：This should not be run as administrator. The mount point may not be accessible by your account normally，only by the administrator.

**Comment by ihaveamac** [comment]
if you’re not manually running as Administrator, UAC is probably disabled.

**Comment by david-zzj** [comment]
when i turn off the UAC，it working fine！！thx
by the way，nand cid where i can get it？my b9s console already have otp.bin，boot9.bin，seeddb.bin，nand.bin，except cid file...what's the cid file look like？

**Comment by ihaveamac** [comment]
do you have essential.exefs? it was generated by GodMode9.

**Comment by ihaveamac** [comment]
2c6e3b0dd53284ce366b4e5ecfe55c17b13dd49a allows it to work when UAC is off. This was only an issue on Windows 7 I think.

**Comment by david-zzj** [comment]
actually，my console already bricked，and i want this tool can help me do something with the bricked nand.bin. lol...so i can‘t get essential.exefs with gm9.

**Comment by ihaveamac** [comment]
when #7 is implemented, the nand cid shouldn't be needed.

**Comment by david-zzj** [comment]
Can I find out nand CID of broken console via Arduino ？

**Comment by ihaveamac** [comment]
I wouldn't know that

**Comment by ihaveamac** [comment]
Since the main problem of this issue was solved, this can be closed now

**Comment by ihaveamac** [comment]
@david-zzj try v1.1, you shouldn't need the cid anymore

**Comment by david-zzj** [comment]
wow, it's a great worked, i will try it soon.

**Comment by david-zzj** [comment]
v1.1 worked!!! i provide nand.bin and the otp.bin , driver Z:  was list normal. Big thanks to you!!!

fuse-3ds v1.1 - https://github.com/ihaveamac/fuse-3ds
Attempting to generate Counter for CTR/TWL areas. If errors occur, provide the CID manually.
Counter for CTR area automatically generated.
Counter for TWL area automatically generated.
ncsd idx:0 fstype:1 crypttype:1 offset:00000000 size:0b100000 /twl_full.img
twl  idx:0                      offset:00012e00 size:08fb5200 /twln.img
twl  idx:1                      offset:09011a00 size:020b6600 /twlp.img
ncsd idx:1 fstype:4 crypttype:2 offset:0b100000 size:00030000 /agbsave.bin
ncsd idx:2 fstype:3 crypttype:2 offset:0b130000 size:00400000 /firm0.bin
ncsd idx:3 fstype:3 crypttype:2 offset:0b530000 size:00400000 /firm1.bin
ncsd idx:4 fstype:1 crypttype:2 offset:0b930000 size:2f5d0000 /ctrnand_full.img
ctr  idx:0                      offset:0b95ca00 size:2f3e3600 /ctrnand_fat.img
The service fuse-3ds has been started.
