### ISSUE TITLE
Nintendo DS ROM support

### ISSUE THREAD

**Issue by ihaveamac** [ihaveamac/fuse-3ds#12]
Would be nice to browse DS and DSi games like GodMode9.

**Comment by ihaveamac** [comment]
aa230f4f3dc47ad52f1a94cdb035e0f7efbe897e implements this, needs more testing (only tried with 5 DS games so far, see if DSi also works, some special titles with no data dir, etc)

**Comment by ihaveamac** [comment]
Still need to implement sub-mounting.

@TurdPooCharger you mentioned on gbatemp that you wanted this, you can try it now if you want (install python, then this using pip; or wait until i can provide an exe if you can't). Until I add sub-mounts (so you can just open a cia and it shows the contents of the srl), you will need to do it a second time for the file inside

**Comment by TurdPooCharger** [comment]
Oh wow, you went and did it? Stoked! :smile:

@ihaveamac, I'll give a go and try to get back with results by week's end. Will need to re-familiarize myself with python, check if the three anti-virus programs I got running clashes with fuse-3ds, and look out for whatever weirdness pops up in Windows 8.1 (Windows 10 can stay the back burning with Linux-based OS).

**Comment by ihaveamac** [comment]
sub-mounts implemented in dcf2e2ccab69e8ee3e5c7986b75774d56679336f

**Comment by ihaveamac** [comment]
Feature should be finished enough to make a new release. Best games to try would probably be a few from early releases (2004, etc), mid-lifespan, and late-lifespan.

**Comment by ihaveamac** [comment]
[v1.2b1](https://github.com/ihaveamac/fuse-3ds/releases/tag/v1.2b1) contains a standalone executable to make testing easier.

**Comment by TurdPooCharger** [comment]
Sorry I haven't gotten back to you earlier. Been doing some brake caliper rebuilding (got stuck with this dust boot that ripped :/), GBAtemp forum helping out other users (mostly SD card stuff), and trying to psych myself into reading fuse-3ds guide top-to-bottom before I went at it. 
**
OKAY, coffee being brewed and full attention to program. Let's see what's it got. :)

**Comment by ihaveamac** [comment]
using fuse-3ds should be straightforward once you set up boot9/seeddb.

**Comment by TurdPooCharger** [comment]
After some hiccups waiting for GBAtemp to come back, Avast giving the clear, sleep from the ensuing hard crash of the coffee, boot9/seeddb retrieval, it's up and running.

![fuse-3ds_installed](https://user-images.githubusercontent.com/35666439/41821430-bbe17b04-77ae-11e8-90f9-d408fbbddee3.png)

You have any particular requests in what to test for? I was thinking of fuse-3ds vs GodMode9 and the various other (misc. 3DS + NDS programs). Select games to test for by type: DSiWare (cia), .nds roms (DS, DSi-enhanced, DSi??), size (8, 16, 32, 64, 256 MB), game save type??, [USA/JPN/EUR,etc] region.

I will be doing files hash comparison to see if files output match to other extractors.

**NDS/3DS editing tool inventory (in no particular order)**

- DSBuff
- DSLazy
- kiwi.ds' NDS Editor
- NDSTool
- Tahaxan
- NitroExplorer2b
- 3DSLazy

**Comment by ihaveamac** [comment]
I am mostly just concerned if all files from an nds/srl are identical to files extracted using ndstool/GodMode9/Tinke/etc. (first two lack proper Shift-JIS support, so filenames encoded with this will only appear properly in fuse-3ds and maybe some other tools). Things like save type are irrelevant to this. Format shouldn't have changed between any files of any year, but I don't know for sure, that's why this should be tested more.

Outside of that any tool should work with files directly inside a mount point. If any programs require administrator, do not use a drive letter as a mount point to use them with files directly inside.

**Comment by ihaveamac** [comment]
Some programs like VGMTrans are an order of magnitude slower when opening files inside mounts, rather than from an NTFS drive directly (e.g. 9s to 3m19s).

**Comment by TurdPooCharger** [comment]
Had to detour for milk pickup run as per my father's request. lol

Testing is underway. Since you seem keen on gunning for Tinke and GodMode9, I'm bench marking fuse-3ds against those two. Five nds roms were selected out of preference and (size.  

- Fuse-3ds worked smoothly and went without a hitch. :+1: 
- Tinke crashed my computer hard 3rd rom in. Had to hard reboot. Bad program.
- GodMode9 still on standby due to the crash.

Gonna hash check and tabulate the differences in their extractions on a spreadsheet.

**Comment by ihaveamac** [comment]
There's not a lot I can do to improve speed of tiny reads (cache path lookup, allow unsafe reads, etc). VGMTrans in particular reads files mostly 0x1000 at a time. At the very least it managed to work.

**Comment by ihaveamac** [comment]
hardcoded banner size fixed in 90e9824af6ac9a36595b94c86086be267cf0f1fb

**Comment by ihaveamac** [comment]
[v1.2b2](https://github.com/ihaveamac/fuse-3ds/releases/tag/v1.2b2) contains the banner size fix.

**Comment by TurdPooCharger** [comment]
@ihaveamac, I have a good feeling what Battery Test No.2, or round 2 vs GM9 will be like (will test this release regardless of that guess). The third test will deal with DSiWare cias.

What I'm curious is how it'll fare against Tinke. There were some differences spotted from quick glances between the two. I'll save this one for No.4.

**Comment by ihaveamac** [comment]
Just add an exception or something. This isn’t really related to this issue.

**Comment by TurdPooCharger** [comment]
**Battery Test No.2 - fuse-3ds v1.2b2 vs GodMode9 v1.6.3-101 nightly [.nds, SRL roms]**
Basically a repeat as Test No.1.

:+1:  - **Title:** 0560 - Cooking Mama (US)
:+1:  * - **Title:** 3398 - Fire Emblem - Shadow Dragon (US) 
:+1:  - **Title:** 5200 - Professor Layton and the Unwound Future (US)
:+1:  - **Title:** 5367 - Golden Sun - Dark Dawn (US)
:+1:  - **Title:** Pokemon - Black Version 2 (USA, Europe) (NDSi Enhanced) [b]

**Comment:** Every files match in cross comparison in both name and hash, * save for the text files in Fire Emblem with Japanese naming (they still match in hash).

***
***

**Battery Test No.3 - fuse-3ds v1.2b2 vs GodMode9 v1.6.3-101 nightly [DSiWare cia roms]**
Games were acquired through _that other shop_ and dumped into CIA format through GM9-v1.6.3-101.

**Title:** Shantae Risky's Revenge (USA)
**CRC32:** 46BAAB4E
**TWL TitleID:** 000300044B533345
**Product Code:** TWL-KS3E
**Size:** 15.9 MB
**Differences:**
**[Left: fuse-3ds // Right: GodMode9]**
- 0000.017a484f.nds // 0000.017A484F.app
***
**Title:** Soul of Darkness (EUR)
**CRC32:** FA4B2362
**TWL TitleID:** 000300044B534B56
**Product Code:** TWL-KSKV
**Size:** 9.48 MB
**Differences:**
- 0000.00000000.nds // 0000.00000000.app
***
**Title:** The Oregon Trail (USA)
**CRC32:** ABBB0A8A
**TWL TitleID:** 000300044B4F5245
**Product Code:** TWL-KORE
**Size:** 11.9 MB
**Differences:**
-  0000.3876b2e1.nds // 0000.3876B2E1.app
***
**Title:** WarioWare Touched! DL (USA)
**CRC32:** 51AD2E35
**TWL TitleID:** 000300045A324154
**Product Code:** TWL-Z2AT
**Size:** 27.7 MB
**Differences:**
-  0000.00000002.nds // 0000.00000002.app
- decrypted.cfa , 0001.00000003.ncch // 0001.00000003.app
***
**Title:** Zelda Four Swords (JPN)
**CRC32:** 718CF667
**TWL TitleID:** 000300044B51394A
**Product Code:** TWL-KQ9J
**Size:** 13.4 MB
**Differences:**
- 0000.00000002.nds // 0000.00000002.app
***
**Comment:** fuse-3ds did very well in this test run. All files again match in hash and names. Of course, the .nds vs .app extension is explainable when Nintendo migrated DSi titles to the 3DS, they've changed this to match it more in line with the 3DS rom standards.

The WarioWare game is one of the very rare DSiWare titles that has an e-manual. fuse-3ds makes two copies of that e-manual. The _decrypted.cfa_ was found in the decompile folder **0001.00000003**. It is the same as _0001.00000003.ncch_ found one directory level back, which is the same as _0001.00000003.app_ from GodMode9.

**Comment by TurdPooCharger** [comment]
**Battery Test No.4 - fuse-3ds v1.2b2 vs Tinke v0.9.2-dev [.nds, SRL roms]**

**Title:** 0560 - Cooking Mama (US)
**Differences:**
_What fuse-3ds has that Tinke is missing._ 
- header.bin 

_What Tinke has that fuse-3ds is missing._ 
- `ftc` folder with fat.bin , fnt.bin , rom.nds (recopied game)
***
Title: 3398 - Fire Emblem - Shadow Dragon (US)
**Differences:**
**[Left: fuse-3ds // Right: Tinke]**
- arm9overlay.bin // y9.bin

_What fuse-3ds has that Tinke is missing._ 
- header.bin

_What Tinke has that fuse-3ds is missing._ 
- `ftc` folder with fat.bin , fnt.bin , various overlay files , rom.nds
***
Title: 5200 - Professor Layton and the Unwound Future (US)
**Differences:**
- arm9overlay.bin // y9.bin

_What fuse-3ds has that Tinke is missing._ 
- header.bin

_What Tinke has that fuse-3ds is missing._ 
- `ftc` folder with fat.bin , fnt.bin , various overlay files , rom.nds
***
Title: 5367 - Golden Sun - Dark Dawn (US)
- arm9overlay.bin // y9.bin

_What fuse-3ds has that Tinke is missing._ 
- header.bin

_What Tinke has that fuse-3ds is missing._ 
- `ftc` folder with fat.bin , fnt.bin , various overlay files , rom.nds 
***
Title: Pokemon - Black Version 2 (USA, Europe) (NDSi Enhanced) [b]
**Differences:**
- arm9overlay.bin // y9.bin

_What fuse-3ds has that Tinke is missing._ 
- arm7i.bin , arm9i.bin , banner.bin , header.bin

_What Tinke has that fuse-3ds is missing._ 
- `ftc` folder with banner.bin , fat.bin , fnt.bin , various overlay files , rom.nds 
***
**Comment:** I'm not entirely sure how to interpret the results of this run as the `ftc` folder is something I'm not familiar with. If I had to guess what those overlay files are, they're the rom in piece-wise subsections for some sort of game editing purpose. It appears fuse-3ds has bloodied Tinke on everything else.

**Comment by ihaveamac** [comment]
`ftc` probably contains extra files that aren't needed as much. I followed GodMode9's layout which doesn't include raw versions of the File Name Table or File Allocation Table.

**Comment by TurdPooCharger** [comment]
Just for kicks, I got two more test runs for your fuse-3ds go up against: DSBuff and DSLazy. Both of them uses NDStool as its basis.

**Comment by ihaveamac** [comment]
no idea what's going on with the extra bytes, GodMode9 doesn't display them, ndstool does.

**Comment by ihaveamac** [comment]
https://github.com/devkitPro/ndstool/blob/313b0be6440d3087b6d433c3ea057605d2c95197/source/header.cpp#L585-L595

1cb275e04b342c86683855dc4933862854a28673 ARM9 footer will be read now according to what ndstool does

**Comment by d0k3** [comment]
@TurdPooCharger - can you add the CRC32s of the rom dumps you tested?

**Comment by TurdPooCharger** [comment]
@d0k3, I was beginning to wonder when you'd pop up. :smiley:

Check the posts that have **Battery Test No.1 - fuse-3ds v1.2b1 vs GodMode9 v1.6.3-101 nightly** and **Battery Test No.3 - fuse-3ds v1.2b2 vs GodMode9 v1.6.3-101 nightly [DSiWare cia roms]** for the hashes. 

Double check the arm9.bin footer for DSi, DSi enhanced, and DSiWare games too as DSBuff / DSLazy / NDSTool can't handle those so there isn't something for fuse-3ds & GodMode9 to cross compare against for these titles.

Anyway, you guys got the rest of this? I got some car brake calipers that needs some tending. If ever you get your hands dirty in rebuilding brake dust seals, use (Sil-Gylde) lube! General life tip, rubber tears when you force it in dry lol.

**Comment by ihaveamac** [comment]
I assume this could be considered complete enough. It has been tested with various games and works fine. Probably won't bother with extracting overlay files unless there's enough requests for it and/or it's not too complicated.

New release won't be put up until PyInstaller supports Python 3.7.0.

**Comment by ihaveamac** [comment]
Changed my mind: I'll put out another beta release using Python 3.6.6, but a stable release won't happen until 3.7.0 works.

About overlays: I'll see how difficult it is to read them.
