### ISSUE TITLE
Problem Decrypted.cxi (Bug)

### ISSUE THREAD

**Issue by GitMathHub** [ihaveamac/fuse-3ds#13]
Hi!

I found one bug: if you try to extract a decrypted.cxi smaller than 1 Gb the extraction keeps going on and the file you are copying becomes bigger and bigger...

One hint: Is it possible to add a feature that you can simply decrypt whole ROM in a 3ds format for example?

Thanks!

GM

**Comment by ihaveamac** [comment]
what platform and fuse-3ds version? I don't remember encountering a thing like this.

**Comment by GitMathHub** [comment]
Latest fuse-3ds version on windows 10 Professional x64 latest update.

**Comment by GitMathHub** [comment]
Excuse-me! I found the problem. I use Teracopy File manager instead of the default one. I used Microsoft explorer and everything went fine. I'm so sorry...
What about the other feature? ;-)

**Comment by ihaveamac** [comment]
TeraCopy likely doesn't check the file size and continues attempting to read until given no data. Notepad++ does this too. 997f33300426180fde7b05bb28e3a89afdadcbac should fix this for all mount scripts.

> Is it possible to add a feature that you can simply decrypt whole ROM in a 3ds format for example?

I don't think this feature belongs here, other tools could do it. it was created with the idea that you don't have to directly decrypt.

**Comment by ihaveamac** [comment]
[release v1.0b8](https://github.com/ihaveamac/fuse-3ds/releases/tag/v1.0b8) fixes the main issue of applications reading too much.
