### ISSUE TITLE
Malware Alert in Avast

### ISSUE THREAD

**Issue by CecilFF4** [ihaveamac/fuse-3ds#15]
fuse-3ds-1.0b8-win64.zip comes up in Avast as infected with Malware-gen.

**Comment by ihaveamac** [comment]
does win32 show the same? both were built on the same virtual machine.

**Comment by CecilFF4** [comment]
No issues with the 32-bit version. I'm on Win10, btw.

**Comment by ihaveamac** [comment]
I will try re-building the win64 exe after completely removing Python 3.6.5 64-bit

**Comment by ihaveamac** [comment]
try this newly built one: [fuse-3ds-1.0b8-win64.zip](https://github.com/ihaveamac/fuse-3ds/files/2021289/fuse-3ds-1.0b8-win64.zip)

**Comment by CecilFF4** [comment]
Clean as a whistle. I was a little worried and was holding off using this. Thanks!

**Comment by ihaveamac** [comment]
MSE didn't detect anything fwiw.

**Comment by ihaveamac** [comment]
release updated: https://github.com/ihaveamac/fuse-3ds/releases/tag/v1.0b8
