### ISSUE TITLE
Can't mount system title NCCH

### ISSUE THREAD

**Issue by CecilFF4** [ihaveamac/fuse-3ds#20]
Using the latest fuse with an updated seeddb, I cannot mount any system title apps, even when the hex for those reveal an obvious NCCH magic. Those with .code decompress the code and then just fail to mount, to directory or to a drive letter. Those without .code don't mount, either.

An example I'm attempting to mount in fuse: `ctrnand\title\00040138\20000002\content\0000002f.app`. The exefs of that (according to godmode9) solely contains a .firm file required for uninstalling b9s (or for fixing a faulty FIRM partition).

**Comment by ihaveamac** [comment]
please post the output of fuse-3ds when you try to mount.

**Comment by CecilFF4** [comment]
The console didn't say anything out of the ordinary; just that the service started, but the mounted location wouldn't show any content. Despite restarting my computer numerous times last night during these tests, it's apparently working right now, and I can't explain what's different. So, I guess it was just something with my computer. Sorry to bother you with this.
