### ISSUE TITLE
Suggestion: Provide virtual encrypted/decrypted file for the whole file

### ISSUE THREAD

**Issue by mariomadproductions** [ihaveamac/fuse-3ds#23]
Not just individual (stripped down?) NCCHs.

**Comment by ihaveamac** [comment]
You mean for CCI/CIA/{something else}? It's probably not worth the trouble for it. But maybe if I can easily do the same thing I did for NCCH for other types.

**Comment by mariomadproductions** [comment]
For CCI/CIA. Is there a reliable encryptor/decryptor for PC for those already?

**Comment by ihaveamac** [comment]
I might consider what is needed for CIA. What's the point for CCI?

**Comment by mariomadproductions** [comment]
I wanted it for the "decrypted checksum" fields in the No-Intro 3DS ROM database.

Not sure there is much use in those fields anymore though. Though I have a feeling decrypted ROMs are more compressible.

**Comment by ihaveamac** [comment]
decrypted checksum will probably be invalid due to small garbage in the ExeFS (end of .code section) on titles using extra crypto. I never thought it was worth fixing because it didn't impact functionality, and it would be really annoying to do so.

**Comment by ihaveamac** [comment]
Doing this for CIA would be very difficult unless only the titlekey layer is removed. This is because the SHA256 of the entire file would have to be regenerated if the content is modified.
