### ISSUE TITLE
Mount from CDN?

### ISSUE THREAD

**Issue by mariomadproductions** [ihaveamac/fuse-3ds#25]
This might be a bit out of reach of what you want to do with this program, but could you make it so it can mount contents actually on the CDN? The specific URL could be specified in settings, or hardcoded - it doesn't matter as all CDN URLs return the same files. It wouldn't download the whole thing - it would, like JNUSTool, just allow you to browse the files and download specific ones as wanted.

**Comment by ihaveamac** [comment]
This would be difficult to pull off and I don't think it's worth doing here. Main reasons are I would need to implement some kind of cache (and keep track of which chunks were downloaded), or send an endless stream of requests for the same content. This is something better for another tool.
