### ISSUE TITLE
No RomFS folder when mounting CCI of Captain Toad: Treasure Tracker (Europe and Japan)

### ISSUE THREAD

**Issue by mariomadproductions** [ihaveamac/fuse-3ds#26]
fuse-3ds v1.2b3 windows 32bit. I don't get any errors in the command line window. They work with other tools. 

The MD5 of the Europe CCI is 7850923CAE79964A3828938C05BBC54C and the MD5 of the Japan CCI is 2534406349CCB36ED03830994B77C255.

You can PM me [on GBATemp]
(https://gbatemp.net/members/hiccup.230145/) about this if you want.

**Comment by ihaveamac** [comment]
already fixed in 2387f44ce1ee43bd1bdff3118231ca7fe10fe75b

**Comment by mariomadproductions** [comment]
Thanks. Do you also have a 64-bit build?

**Comment by ihaveamac** [comment]
32-bit was uploaded since you only mentioned 32-bit, but here: [fuse-3ds-1.2b4.dev1-win64.zip](https://github.com/ihaveamac/fuse-3ds/files/2196136/fuse-3ds-1.2b4.dev1-win64.zip)
