### ISSUE TITLE
Add A .desktop File for Linux

### ISSUE THREAD

**Issue by CuriousTommy** [ihaveamac/fuse-3ds#29]
It would be nice to have a way to launch the GUI application on Linux without needing to use terminal. Would you be able to provide a `fuse3ds.desktop` file? You can have it automatically install to `~/.local/share/applications`.

Here is a [guide](https://www.maketecheasier.com/create-desktop-file-linux/) to creating a `.desktop` file.

**Comment by ihaveamac** [comment]
Is it always `~/.local/share/applications`, or is it based off an environment variable/some other config? I don't want to hardcode a path if there's a possibility of it changing.

**Comment by CuriousTommy** [comment]
I am actually not sure... I will ask about it on linuxquestion and let you know.

**Comment by CuriousTommy** [comment]
The XDG Base Directory states that `.desktop` files should be located in `$XDG_DATA_HOME/applications/`. If `$XDG_DATA_HOME` is not defined, then use `$HOME/.local/share` (so the path would be `$HOME/.local/share/applications/`)

You can read more about it [here under "Environment variables"](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) and [here](https://standards.freedesktop.org/menu-spec/latest/ar01s02.html).

[Credit goes to this Reddit post](https://www.reddit.com/r/linuxquestions/comments/9gm14u/is_localshareapplications_always_the_standard/e657p4g/).

**Comment by ihaveamac** [comment]
I will probably include a .desktop file and have it installed with a command-line argument (e.g. `python3 -mfuse3ds --install-desktop-entry`). Doing this via setup.py would mean it's always installed, even if the user didn't install the gui. But I can't check if the user did install the gui via setup.py.

**Comment by ihaveamac** [comment]
Using `python3 -mfuse3ds --install-desktop-entry [/path/to/share]` writes fuse3ds.desktop and icons. It uses `$XDG_DATA_HOME` by default, unless you provide a prefix (e.g. `/usr/share`).

**Comment by CuriousTommy** [comment]
I just did a quick test, perfect! Just make sure you make a note about this on the readme.
