### ISSUE TITLE
"KeyslotMissingError: normal key for keyslot 0x40 is not set up"

### ISSUE THREAD

**Issue by mariomadproductions** [ihaveamac/fuse-3ds#3]
``Warning: TMD Content size and filesize of 00000000 are different.
Failed to mount /0000.00000000.ncch: KeyslotMissingError: normal key for keyslot 0x40 is not set up
Failed to mount /0001.00000001.ncch: KeyslotMissingError: normal key for keyslot 0x40 is not set up
``
i'm trying to mount CDN contents for 00040000001ad700. I'm using v1.0b6 64-bit Windows exe.

**Comment by ihaveamac** [comment]
make sure your contents are valid. this title works for me.

**Comment by mariomadproductions** [comment]
I'm a bit of an idiot. I download the title using nustool, which decrypted the CDN encryption. Does fuse-3ds support CDN contents without CDN encryption?

**Comment by ihaveamac** [comment]
only if the encryption bit on each content in the tmd is not on. otherwise you can try renaming the tmd to 00000000.tmd and try the titledir mount.

**Comment by mariomadproductions** [comment]
I got it to work with the NCCH mount. But that's a useful tip regarding the titledir mount.

**Comment by ihaveamac** [comment]
turns out `--dec-key` was broken the whole time since I forgot to move it to a newer crypto system.
