### ISSUE TITLE
What happened to the copy on pypi?

### ISSUE THREAD

**Issue by jack980517** [ihaveamac/fuse-3ds#30]
I installed it via `pip3 install fuse-3ds` when the latest version was 1.2b4, and now pip says the package cannot be found. Why is it removed? Can you bring it back to pypi?

**Comment by ihaveamac** [comment]
It was never on pypi.

**Comment by ihaveamac** [comment]
Starting with 1.3 I am now uploading releases to PyPI. If it was on the index before, it wasn't from me.

https://pypi.org/project/fuse-3ds/
