### ISSUE TITLE
Yo-Kai Watch RomFS only shows audio and movies, even though there should be more.

### ISSUE THREAD

**Issue by jewelforest** [ihaveamac/fuse-3ds#35]
This happens for all 3 main games.
Affected titles:
Yo-kai Watch
Yo-kai Watch 2: Bony Spirits
Yo-kai Watch 2: Fleshy Souls
Yo-kai Watch 2: Psychic Specters
Yo-kai Watch 3: Sushi
Yo-kai Watch 3: Tempura
Yo-kai Watch 3: Sukiyaki
Yo-kai Watch 3 (International release)

I have not tested the side games.

Directory in fuse3ds:
<img width="1152" alt="Capture" src="https://user-images.githubusercontent.com/37014961/55522200-769f1e00-56cb-11e9-9a59-a45be1b1c8b5.PNG">
This directory shows audio and movies.
It should contain more than just that, including graphics, models, textures, dialogue, etc.
No other directory in the game (that I can find) would make sense to hold those files instead.

I have tried the following:
Godmode9 decryption
Dumping my own cartridges

**Comment by ihaveamac** [comment]
It is highly unlikely to be a different RomFS format where the files are somewhere else. I would guess most of the data would be in `yw1_a.fa` for this game. If you're sure it's not, please check with other tools like GodMode9, ctrtool, or 3dstool.

**Comment by jewelforest** [comment]
Sorry, I am inexperienced. How would I look into yw1_a.fa ?

**Comment by luigoalma** [comment]
It's a format specific to the game, of which I don't know myself what it is.
Also those are all the files of the game's romfs, with ctrtool too

**Comment by ihaveamac** [comment]
Most games have unique formats that need extra tools to extract, and most of the other assets are likely to be in this large file. I wouldn't know what tools are needed to extract this unfortunately. In any case, this is unlikely to be a fuse-3ds issue.

**Comment by HidegonSan** [comment]
https://gbatemp.net/threads/reading-and-extracting-from-yo-kai-watch-filesystem-yw1_a-fa-yw2_a-fa-yw3_a-fa.535136/

**Comment by LandonBoi123** [comment]
you can open the files in Karameru, a program inside of Kuriimu
