### ISSUE TITLE
Add new configuration directory

### ISSUE THREAD

**Issue by ihaveamac** [ihaveamac/fuse-3ds#8]
Maybe I should add a specific one? Some config files could go here. Don't know exactly what though.
* Windows: `%APPDATA%\fuse3ds`
* macOS: `~/Library/Application Support/fuse3ds` (or maybe use the one below too)
* Linux: `~/.config/fuse3ds`

**Comment by CuriousTommy** [comment]
For Linux, does this application support the [XDG Base Directory Standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)? That would be nice to have.

Also for MacOS, you should support both, have it look at the `Application Support` first if the files are there, then check in the `.config` folder.

**Comment by ihaveamac** [comment]
It doesn't use a standard like that right now, since it has no configuration directory specific to this application. The only paths it checks right now for boot9/seeddb are current dir, `~/.3ds`, and `~/3ds`. The first one is taken from some of yellows8's projects and shared with another one of mine, the second is easier for Windows users to create, because Windows/File Explorer doesn't easily allow creating directories starting with a period.

This new one would be specific to fuse-3ds and would store more than just boot9/seeddb (if the user wants to put them here). I would need to read more about the standard but it seems `XDG_CONFIG_HOME` generally points to `$HOME/.config`.

**Comment by ihaveamac** [comment]
URL is now https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html (first one did not load for me anymore)

For fuse-3ds specific configuration (e.g. update check/notify settings), I'm thinking of going with only one fixed path per OS: `%APPDATA%\fuse-3ds`, `~/Library/Application Support/fuse3ds`, and `$XDG_CONFIG_HOME/fuse-3ds`. Unlike the one that store boot9/seeddb/etc, which can be different paths, since some other programs may now support them (e.g. [ctrcdnfetch](https://github.com/luigoalma/ctrcdnfetch) uses these paths to read certificates).

**Comment by ihaveamac** [comment]
03d19318d8b8ca6e3f8cde6b26d7ad506f19da88 new config_dir variable that contains these paths, but is currently unused.

For Linux, it uses `$XDG_CONFIG_HOME/fuse-3ds` if it's set, checks paths of `$XDG_CONFIG_DIRS` (defaults to `/etc/xdg` if not set) to see if `fuse-3ds` _already exists_ in one of them, then falls back to `~/.config/fuse-3ds`. I think this is how the standard works.

**Comment by CuriousTommy** [comment]
The only concern I have with using `XDG_CONFIG_DIRS` is that the user may be required to use root to store files in there (especially if the default location is `fuse-3ds`), otherwise everything is fine (if you intend to keep it in a config directory).

Thanks again for using the XDG standard!

**Comment by ihaveamac** [comment]
According to https://wiki.archlinux.org/index.php/XDG_Base_Directory `XDG_CONFIG_DIRS` is for system directories, and defaults to `/etc/xdg`. Though the standard also says that `XDG_CONFIG_DIRS` has a list of extra directories to search in addition to `XDG_CONFIG_HOME` (if it's not set). A configuration directory would never be automatically made in any `XDG_CONFIG_DIRS` directories, only used if the user explicitly sets it up.

**Comment by ihaveamac** [comment]
Commits 3dfc0245b0dce7055119cad2c986b9716bc16e7f 8c82ce665c0f4b174c0d71f991580a13d19fbb29 aa75770ddf967f993754400ae139fc7e575e3a16 58b45295425ca04fecdec893230e0f2d4cfd1a4a add support for using `update.cfg` in this new configuration directory. Only tested on Mac so far.

**Comment by ihaveamac** [comment]
Tested on Windows & Linux now (including `XDG_CONFIG_HOME`).

**Comment by CuriousTommy** [comment]
> fuse-3ds would never automatically create a config in any XDG_CONFIG_DIRS directories, only used if the user explicitly sets it up, knowing that it may require elevated privileges.

Makes sense. I was thinking why you need to use `XDG_CONFIG_DIRS`, but I can see why you want to have support for it.
